# Generated by Django 6.0.7 on 2026-07-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpro', '0004_alter_employee_email_alter_register_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='images')),
            ],
        ),
    ]
